{
 "title": "Router Status",
 "description": "Router Status",
 "tags": [
  "Internet",
  "Router"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Asus Router", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Internet status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  wanStatus\nFROM monitorTable\nORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Uptime\nFROM monitorTable ;"
    }
   ]
  },
  {
   "title": "WAN In",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  internetRXSpeed\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "WiFi 5G Out",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  5GHXTXSpeed\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "LAN Out",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  wiredTXSpeed\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "WiFi 2.4G Out",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  2GHXTXSpeed\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "WAN Out",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  internetTXSpeed\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "Bandwidth In",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  bridgeRXSpeed\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "WiFi 5G In",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  5GHXRXSpeed\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "LAN In",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  wiredRXSpeed\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "WiFi 2.4G In",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  2GHXRXSpeed\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "Bandwidth Out",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  bridgeTXSpeed\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    memUSed/memTotal\nFROM monitorTable"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cpu1Usage/cpu1Total AS \"cpu1PC\"\nFROM monitorTable"
    },
    {
     "rawSql": "SELECT\n  cpu2Usage/cpu2Total AS \"cpu2PC\"\nFROM monitorTable"
    },
    {
     "rawSql": "SELECT\n  cpu3Usage/cpu3Total AS \"cpu3PC\"\nFROM monitorTable"
    },
    {
     "rawSql": "SELECT\n  cpu4Usage/cpu4Total AS \"cpu4PC\"\nFROM monitorTable"
    }
   ]
  },
  {
   "title": "Sent/Recieve Data",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  recvData\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    },
    {
     "rawSql": "SELECT\n  timeStamp AS \"time\",\n  sentData\nFROM monitorTable\nWHERE\n  $__timeFilter(timeStamp)\nORDER BY timeStamp"
    }
   ]
  },
  {
   "title": "Connected Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  deviceCount\nFROM monitorTable;"
    }
   ]
  }
 ]
}